-- M5.5: instantáneas para análisis / entrenamiento de IA.

-- Instantáneas del escenario (para análisis estadístico y entrenamiento de IA).
CREATE TABLE IF NOT EXISTS snapshots (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  captured_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  symbol           TEXT NOT NULL,
  interval         TEXT NOT NULL,
  price            DOUBLE PRECISION NOT NULL,
  atr              DOUBLE PRECISION,
  adx              DOUBLE PRECISION,
  regime_label     TEXT,
  net              DOUBLE PRECISION,
  prob_buy         DOUBLE PRECISION,
  prob_hold        DOUBLE PRECISION,
  prob_sell        DOUBLE PRECISION,
  action           TEXT,
  direction        TEXT,
  confidence       DOUBLE PRECISION,
  macro_bias       DOUBLE PRECISION,
  funding_rate     DOUBLE PRECISION,
  weekly_trend     DOUBLE PRECISION,
  macro_label      TEXT,
  confluence       TEXT,
  ema_cross_score  DOUBLE PRECISION,
  macd_score       DOUBLE PRECISION,
  rsi14_score      DOUBLE PRECISION,
  rsi14_value      DOUBLE PRECISION,
  bbands_score     DOUBLE PRECISION,
  stoch14_score    DOUBLE PRECISION,
  adx14_value      DOUBLE PRECISION,
  atr14_value      DOUBLE PRECISION,
  reditum_sniper_score DOUBLE PRECISION,
  reditum_poc_score    DOUBLE PRECISION,
  plan_entry       DOUBLE PRECISION,
  plan_stop        DOUBLE PRECISION,
  plan_take_profit DOUBLE PRECISION,
  plan_size        DOUBLE PRECISION,
  plan_rr          DOUBLE PRECISION,
  valid_until      TIMESTAMPTZ,
  outcome_result   TEXT,
  outcome_return_r DOUBLE PRECISION,
  outcome_mfe      DOUBLE PRECISION,
  outcome_mae      DOUBLE PRECISION,
  evaluated_at     TIMESTAMPTZ,
  model_version    TEXT,
  source           TEXT DEFAULT 'manual',
  note             TEXT,
  raw_signal       JSONB NOT NULL
);
SELECT create_hypertable('snapshots', 'captured_at', if_not_exists => TRUE);
